// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	GreetReq
	GreetResq
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreetReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *GreetReq) Reset()                    { *m = GreetReq{} }
func (m *GreetReq) String() string            { return proto.CompactTextString(m) }
func (*GreetReq) ProtoMessage()               {}
func (*GreetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GreetReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GreetReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GreetResq struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *GreetResq) Reset()                    { *m = GreetResq{} }
func (m *GreetResq) String() string            { return proto.CompactTextString(m) }
func (*GreetResq) ProtoMessage()               {}
func (*GreetResq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GreetResq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetReq)(nil), "pb.GreetReq")
	proto.RegisterType((*GreetResq)(nil), "pb.GreetResq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatServer service

type ChatServerClient interface {
	SayHello(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResq, error)
}

type chatServerClient struct {
	cc *grpc.ClientConn
}

func NewChatServerClient(cc *grpc.ClientConn) ChatServerClient {
	return &chatServerClient{cc}
}

func (c *chatServerClient) SayHello(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResq, error) {
	out := new(GreetResq)
	err := grpc.Invoke(ctx, "/pb.ChatServer/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatServer service

type ChatServerServer interface {
	SayHello(context.Context, *GreetReq) (*GreetResq, error)
}

func RegisterChatServerServer(s *grpc.Server, srv ChatServerServer) {
	s.RegisterService(&_ChatServer_serviceDesc, srv)
}

func _ChatServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChatServer/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServerServer).SayHello(ctx, req.(*GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChatServer",
	HandlerType: (*ChatServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ChatServer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe0, 0xe2,
	0x70, 0x2f, 0x4a, 0x4d, 0x2d, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3,
	0x25, 0x98, 0xc0, 0x42, 0x20, 0xa6, 0x92, 0x2c, 0x17, 0x27, 0x54, 0x47, 0x71, 0x21, 0x4c, 0x9a,
	0x11, 0x2e, 0x6d, 0x64, 0xca, 0xc5, 0xe5, 0x9c, 0x91, 0x58, 0x12, 0x0c, 0xb6, 0x48, 0x48, 0x9d,
	0x8b, 0x23, 0x38, 0xb1, 0xd2, 0x23, 0x35, 0x27, 0x27, 0x5f, 0x88, 0x47, 0xaf, 0x20, 0x49, 0x0f,
	0x66, 0x99, 0x14, 0x2f, 0x12, 0xaf, 0xb8, 0x30, 0x89, 0x0d, 0xec, 0x24, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfb, 0x98, 0xcd, 0x3f, 0xa2, 0x00, 0x00, 0x00,
}
